package org.example

import org.example.dsl_script.connect.fluent.ConnectModelBuilder
import org.example.dsl_script.connect.fluent.ConnectorType
import org.example.dsl_script.connect.fluent.EquipmentType

class FluentSample {

    fun sample(connectBuilder : ConnectModelBuilder) {
        val model = connectBuilder
            .plane()
                .id("RP-01")
                .name("SU-58")
                .connectors()
                    .connector()
                        .id("CON-FB-00")
                        .type(ConnectorType.FIBER)
                    .connector()
                        .id("CON-FB-01")
                        .type(ConnectorType.FIBER)
                    .connector()
                        .id("CON-RJ-00")
                        .type(ConnectorType.RJ45)
                    .connector()
                        .id("CON-RJ-01")
                        .type(ConnectorType.RJ45)
            .equipment()
                .id("RAD-01")
                .type(EquipmentType.HF)
                .connectors()
                    .connector()
                        .id("CON-FB-00")
                        .type(ConnectorType.FIBER)
                    .connector()
                        .id("CON-RJ-01")
                        .type(ConnectorType.RJ45)
            .equipment()
                .id("COT-01")
                .type(EquipmentType.RF4_COCKPIT)
                .connectors()
                    .connector()
                        .id("CON-FB-00")
                        .type(ConnectorType.FIBER)
                    .connector()
                        .id("CON-RJ-01")
                        .type(ConnectorType.RJ45)
            .equipment()
                .id("SR-00")
                .type(EquipmentType.RADAR)
                .connectors()
                    .connector()
                        .id("CON-FB-00")
                        .type(ConnectorType.FIBER)
                    .connector()
                        .id("CON-RJ-01")
                        .type(ConnectorType.RJ45)
            .equipment()
                .id("SR-01 ")
                .type(EquipmentType.IR)
                .connectors()
                    .connector()
                        .id("CON-FB-00")
                        .type(ConnectorType.FIBER)
                    .connector()
                        .id("CON-RJ-01")
                        .type(ConnectorType.RJ45)
            .cable()
                .id("CABLE-FB-00")
                .type(ConnectorType.FIBER)
            .cable()
                .id("CABLE-FB-01")
                .type(ConnectorType.FIBER)
            .cable()
                .id("CABLE-RJ-02")
                .type(ConnectorType.RJ45)
            .cable()
                .id("CABLE-RJ-03")
                .type(ConnectorType.RJ45)
            .connect()
                .from("RP-01", "CON-FB-00")
                .to("RAD-01","CON-FB-00")
                .with("CABLE-FB-00")
            .connect()
                .from("RP-01", "CON-FB-01")
                .to("COT-01","CON-FB-00")
                .with("CABLE-FB-01")
            .connect()
                .from("RP-01", "CON-RJ-00")
                .to("SR-00","CON-RJ-01")
                .with("CABLE-RJ-02")
            .connect()
                .from("RP-01", "CON-RJ-01")
                .to("SR-01","CON-RJ-01")
                .with("CABLE-RJ-03")
        .build()
    }

}